# SPDX-FileCopyrightText: Copyright (c) 2025-2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import argparse
import json
import os
import signal
from datetime import datetime, timezone

import httpx
import requests
import sseclient

BASE_URL = "https://grpc.nvcf.nvidia.com"
HEADERS = {
    "Authorization": f"Bearer {os.getenv('NGC_PAK_APIC_BP')}",
    "function-id": "1028d84b-59b2-4770-84a3-72ba11d73976",
}

API_PREFIX = "/v1"


def get_api_url(path):
    return BASE_URL + path


def get_parser():

    parser = argparse.ArgumentParser(
        description="VIA CLI Client - single file summarization & QA",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument(
        "--backend",
        type=str,
        help="Backend server address and port",
        default=os.environ.get("VIA_BACKEND", "http://localhost:8000"),
    )

    mandatory_args = parser.add_argument_group("Mandatory Arguments")
    mandatory_args.add_argument("file", type=str, help="File to add")

    opt_args = parser.add_argument_group("Optional Arguments")
    opt_args.add_argument(
        "--is-image", help="The file to be added is an image", action="store_true"
    )

    opt_args.add_argument(
        "--stream", help="Stream the output using server side events", action="store_true"
    )
    opt_args.add_argument("--chunk-duration", help="Chunk duration in seconds", type=int)
    opt_args.add_argument(
        "--chunk-overlap-duration", help="Chunk overlap duration in seconds", type=int
    )
    opt_args.add_argument(
        "--summary-duration",
        help="Summarize every `summaryDuration` seconds of the video.",
        type=int,
    )
    opt_args.add_argument("--prompt", help="Prompt to use for VLM.", type=str)
    opt_args.add_argument(
        "--caption-summarization-prompt",
        help="Prompt used by CA-RAG to summarize captions generated by VLM."
        " This can be used only when VIA is started with VIA_DEV_API=1.",
        type=str,
    )
    opt_args.add_argument(
        "--summary-aggregation-prompt",
        help="Prompt used by CA-RAG to generate the final summary."
        " This can be used only when VIA is started with VIA_DEV_API=1.",
        type=str,
    )
    opt_args.add_argument(
        "--file-start-offset",
        help="Offset in the media file to start processing from, in seconds",
        type=str,
    )
    opt_args.add_argument(
        "--file-end-offset",
        help="Time in the media file to end processing at, in seconds",
        type=str,
    )
    opt_args.add_argument(
        "--model-temperature", help="Temperature to use while generating from LLM", type=float
    )
    opt_args.add_argument(
        "--model-top-p", help="Top-P to use while generating from LLM", type=float
    )
    opt_args.add_argument("--model-top-k", help="Top-K to use while generating from LLM", type=int)
    opt_args.add_argument(
        "--model-max-tokens", help="Max tokens to use while generating from LLM", type=int
    )
    opt_args.add_argument("--model-seed", help="Seed to use while generating from LLM", type=int)
    opt_args.add_argument(
        "--response-format",
        help="Format of the model output",
        choices=["json_object", "text"],
        default="text",
        type=str,
    )
    opt_args.add_argument("--username", help="Username to access the live stream", type=str)
    opt_args.add_argument("--password", help="Password to access the live stream", type=str)
    opt_args.add_argument("--question", help="Question for Q&A", type=str)
    opt_args.add_argument("--enable-chat", help="Enable Q&A", action="store_true")

    return parser


def convert_seconds_to_string(seconds, need_hour=False, millisec=False):
    seconds_in = seconds
    hours = int(seconds // 3600)
    minutes = int((seconds % 3600) // 60)
    seconds = int(seconds % 60)

    if need_hour or hours > 0:
        ret_str = f"{hours:02d}:{minutes:02d}:{seconds:02d}"
    else:
        ret_str = f"{minutes:02d}:{seconds:02d}"

    if millisec:
        ms = int((seconds_in * 100) % 100)
        ret_str += f".{ms:02d}"
    return ret_str


def check_err_response(response: requests.Response, exit_on_error=False):
    if response.status_code >= 400:
        try:
            err_json = response.json()
            print(f"Request failed, code - {err_json['code']} message - {err_json['message']}")
            if exit_on_error:
                exit(-1)
        except Exception:
            print(response.text)
            print(f"Request failed, {response.text}")
            if exit_on_error:
                exit(-1)


def do_add_file(args, client):
    print("file name is ", str(args.file))
    files = {
        # "file": open(args.file, "rb"),
        # "filename": "/opt/nvidia/rtvi/streams/bp_preview/warehouse.mp4",
        "filename": (None, os.path.abspath(args.file))
    }
    files["purpose"] = (None, "vision")
    files["media_type"] = (None, "image" if args.is_image else "video")

    print(get_api_url(f"{API_PREFIX}/files"))

    result = client.post(get_api_url(f"{API_PREFIX}/files"), files=files, headers=HEADERS)
    print("result is", str(result))
    check_err_response(result, False)
    result_json = result.json()
    print(
        "File added - id: %s, filename %s, bytes %d, purpose %s, media_type %s"
        % (
            result_json["id"],
            result_json["filename"],
            result_json["bytes"],
            result_json["purpose"],
            result_json["media_type"],
        )
    )
    return result_json["id"]


def get_timestamp_str(ts):
    """Get RFC3339 string timestamp"""
    return ts.strftime("%Y-%m-%dT%H:%M:%S") + f".{(int(ts.timestamp() * 1000) % 1000):03d}Z"


def do_add_live_stream(args, client):
    stream_data = {
        "liveStreamUrl": args.file,
        "description": "",
    }
    if args.username:
        stream_data["username"] = args.username
    if args.password:
        stream_data["password"] = args.password

    req_json = {"streams": [stream_data]}

    result = client.post(get_api_url(f"{API_PREFIX}/streams/add"), json=req_json, headers=HEADERS)
    check_err_response(result, True)
    result_json = result.json()
    if result_json.get("errors") and len(result_json["errors"]) > 0:
        error = result_json["errors"][0]
        raise Exception(f"Failed to add live stream: {error.get('error', 'Unknown error')}")
    if result_json.get("results") and len(result_json["results"]) > 0:
        stream_id = result_json["results"][0]["id"]
        print(f"Live stream added - id: {stream_id}")
        return stream_id
    else:
        raise Exception("No results returned from API")


def do_list_models(client):
    result = client.get(get_api_url(f"{API_PREFIX}/models"), headers=HEADERS)
    check_err_response(result, True)
    model_list = result.json()["data"]
    return model_list


def do_summarize(args, id, client):
    models = do_list_models(client)
    req_json = {
        "id": id,
        "model": models[0]["id"],
        "response_format": {"type": args.response_format},
        "enable_chat": args.enable_chat,
    }

    if args.model_temperature is not None:
        req_json["temperature"] = args.model_temperature
    if args.model_seed is not None:
        req_json["seed"] = args.model_seed
    if args.model_top_p is not None:
        req_json["top_p"] = args.model_top_p
    if args.model_top_k is not None:
        req_json["top_k"] = args.model_top_k
    if args.model_max_tokens is not None:
        req_json["max_tokens"] = args.model_max_tokens

    if args.chunk_duration is not None:
        req_json["chunk_duration"] = args.chunk_duration
    if args.chunk_overlap_duration is not None:
        req_json["chunk_overlap_duration"] = args.chunk_overlap_duration
    if args.summary_duration is not None:
        req_json["summary_duration"] = args.summary_duration
    if args.prompt:
        req_json["prompt"] = args.prompt
    if args.caption_summarization_prompt:
        req_json["caption_summarization_prompt"] = args.caption_summarization_prompt
    if args.summary_aggregation_prompt:
        req_json["summary_aggregation_prompt"] = args.summary_aggregation_prompt

    media_info = {}
    if args.file_start_offset is not None:
        media_info["type"] = "offset"
        media_info["start_offset"] = args.file_start_offset
    if args.file_end_offset is not None:
        media_info["type"] = "offset"
        media_info["end_offset"] = args.file_end_offset

    if media_info:
        req_json["media_info"] = media_info

    if args.stream:
        req_json["stream"] = True
        req_json["stream_options"] = {"include_usage": True}

    result = client.post(
        get_api_url(f"{API_PREFIX}/generate_captions"), json=req_json, headers=HEADERS
    )
    check_err_response(result, True)
    if args.stream:
        client = sseclient.SSEClient(result)
        first_response = True
        try:
            for event in client.events():
                data = event.data.strip()
                if data == "[DONE]":
                    print("Summarization Complete")
                    break
                result = json.loads(data)
                if first_response:
                    print("Request ID:", result["id"])
                    print(
                        "Request Creation Time:",
                        datetime.utcfromtimestamp(result["created"]).strftime("%Y-%m-%d %H:%M:%S"),
                    )
                    print("Model:", result["model"])
                    print("----------------------------------------")
                    first_response = False
                print("Object:", result["object"])
                if result["media_info"] and result["media_info"]["type"] == "offset":
                    print(
                        "Media start offset: "
                        + convert_seconds_to_string(result["media_info"]["start_offset"])
                    )
                    print(
                        "Media end offset: "
                        + convert_seconds_to_string(result["media_info"]["end_offset"])
                    )
                if result["media_info"] and result["media_info"]["type"] == "timestamp":
                    print(f"Media start timestamp: {result['media_info']['start_timestamp']}")
                    print(f"Media end timestamp: {result['media_info']['end_timestamp']}")
                    now = datetime.now(timezone.utc)
                    end = datetime.strptime(
                        result["media_info"]["end_timestamp"], "%Y-%m-%dT%H:%M:%S.%fZ"
                    ).replace(tzinfo=timezone.utc)
                    print("Current timestamp: " + get_timestamp_str(now))
                    latency = max(now, end) - min(now, end)
                    print(f"Latency: {latency.seconds} seconds")
                if result["choices"]:
                    print("Response:")
                    print(result["choices"][0]["message"]["content"])
                if result["usage"]:
                    print(f"Chunks processed: {result['usage']['total_chunks_processed']}")
                    print(f"Processing Time: {result['usage']['query_processing_time']} seconds")
                print("----------------------------------------")
        except KeyboardInterrupt:
            print("User interrupted")
    else:
        result = result.json()
        print("Summarization finished")
        print("Request ID:", result["id"])
        print(
            "Request Creation Time:",
            datetime.utcfromtimestamp(result["created"]).strftime("%Y-%m-%d %H:%M:%S"),
        )
        print("Model:", result["model"])
        print("Object:", result["object"])
        if result["media_info"]["type"] == "offset":
            print(
                "Media start offset: "
                + convert_seconds_to_string(result["media_info"]["start_offset"])
            )
            print(
                "Media end offset: " + convert_seconds_to_string(result["media_info"]["end_offset"])
            )
        print(f"Chunks processed: {result['usage']['total_chunks_processed']}")
        print(f"Processing Time: {result['usage']['query_processing_time']} seconds")
        print("Response:")
        print(result["choices"][0]["message"]["content"])


def do_delete_file(file_id, client):
    result = client.delete(get_api_url(f"{API_PREFIX}/files/" + file_id), headers=HEADERS)
    check_err_response(result, True)
    result_json = result.json()
    print("File deleted - id %s, status %r" % (result_json["id"], result_json["deleted"]))


def do_delete_live_stream(file_id, client):
    result = client.delete(get_api_url(f"{API_PREFIX}/streams/delete/" + file_id), headers=HEADERS)
    check_err_response(result, True)
    print("Live stream deleted")


def do_ping(client):
    result = client.get(get_api_url(f"{API_PREFIX}/live"), headers=HEADERS)
    check_err_response(result, True)


def keep_alive_thread(client):
    import time

    while True:
        do_ping(client)
        time.sleep(1)


def main():
    global BASE_URL
    parser = get_parser()
    args = parser.parse_args()
    BASE_URL = args.backend
    timeout = httpx.Timeout(None)  # , connect=60000, read=600000, write=600000, pool=60000)
    limits = httpx.Limits(max_keepalive_connections=5, max_connections=10, keepalive_expiry=6000000)
    # transport = httpx.HTTPTransport(
    #     retries=5,
    #     # pool_limits=httpx.Limits(max_keepalive_connections=5, max_connections=10)
    # )
    with httpx.Client(timeout=timeout, limits=limits) as client:
        file_id = (
            do_add_live_stream(args, client)
            if args.file.startswith("rtsp://")
            else do_add_file(args, client)
        )
        do_summarize(args, file_id, client)
        # if args.enable_chat:
        #     import threading

        #     threading.Thread(target=keep_alive_thread, args=(client,), daemon=True).start()
        while args.enable_chat:
            try:
                question = input("User Question: ")
                do_chat(args, file_id, question, client)
            except KeyboardInterrupt:
                break
        (
            do_delete_live_stream(file_id, client)
            if args.file.startswith("rtsp://")
            else do_delete_file(file_id, client)
        )


if __name__ == "__main__":
    try:

        def quit_gracefully(*args):
            print("GOT INTERRUPT")
            raise KeyboardInterrupt

        signal.signal(signal.SIGINT, quit_gracefully)
        signal.signal(signal.SIGTERM, quit_gracefully)
        # signal.signal(signal.SIGINT, signal.default_int_handler)

        main()
    except requests.exceptions.ConnectionError:
        print("Failed to connect to server")
        exit(-1)
